import json
import networkx as nx
import matplotlib.pyplot as plt
from pyvis.network import Network

# Load deps.json generated by:
# flutter pub deps --json > deps.json
with open("gluttex_home/deps.json", "r") as f:
    data = json.load(f)

# # Initialize graph
# G = nx.DiGraph()



# Define what counts as "internal"
def is_internal(pkg):
    return pkg.startswith("gluttex_") or pkg.startswith("medicom_")


ui_packages = ["gluttex_chef","gluttex_login","gluttex_play","medicom_catalog","gluttex_home","gluttex_medical","gluttex_localiser"]



# Create directed graph
G = nx.DiGraph()

# # Add nodes and edges (excluding third-party)
# our_packages = {pkg["name"] for pkg in data["packages"]}

for pkg in data["packages"]:
    pkg_name = pkg["name"]
    for dep in pkg.get("dependencies", []):
        if is_internal(dep):  # only include in-house deps
            # G.add_node(pkg_name)
            G.add_edge(pkg_name,dep)


# PyVis graph
net = Network(height="100%", width="100%", directed=True, notebook=False)
net.barnes_hut()

# Compute in-degree (number of incoming edges)
in_degrees = dict(G.in_degree())



# Add nodes with size proportional to in-degree
for node in G.nodes():
    size = 15 + in_degrees.get(node, 0) * 8  # base size + scaled by in-degree
    # color = "#ff6666" if node == data["root"] else "#66b3ff"
    if(node in ui_packages):
        color = "#001aff"
    else:
        color = "#ff6666"
    
    # color = "#8400ff" if node == data["root"] else "#66b3ff"

    net.add_node(node, size=size, color=color, image="package.svg", title=f"{node} dependencies: {len(list(G.successors(node)))}")

# Add edges
for source, target in G.edges():
    net.add_edge(source, target)

# Save to HTML
net.show("dependencies.html")