import json
import networkx as nx
import matplotlib.pyplot as plt
from pyvis.network import Network

# Load deps.json generated by:
# flutter pub deps --json > deps.json
with open("deps.json", "r") as f:
    data = json.load(f)

# # Initialize graph
# G = nx.DiGraph()

internal_packages = ["gluttex_chef",     "gluttex_launcher" ,"gluttex_io","gluttex_ui"     ,"gluttex_event"     ,"gluttex_core","gluttex_impl_app","gluttex_impl_mediation","gluttex_login","gluttex_play","gluttex_constants","gluttex_home","gluttex_impl_business","gluttex_localiser"  ,"gluttex_medical","locator","medicom_catalog"]

ui_packages = ["gluttex_chef",     "gluttex_launcher","gluttex_ui","gluttex_login","gluttex_play","medicom_catalog","gluttex_home","gluttex_medical","gluttex_localiser"]

# Define what counts as "internal"
def is_internal(pkg):
    return pkg in internal_packages

# Create directed graph
G = nx.DiGraph()

# # Add nodes and edges (excluding third-party)
# our_packages = {pkg["name"] for pkg in data["packages"]}

for pkg in data["packages"]:
    pkg_name = pkg["name"]
    for dep in pkg.get("dependencies", []):
        # if is_internal(dep):  # only include in-house deps
        G.add_node(pkg_name)
        if is_internal(pkg_name):
            G.add_edge(pkg_name,dep)


# PyVis graph
net = Network(height="100%", width="100%", directed=True, notebook=False)
net.barnes_hut()

# Compute in-degree (number of incoming edges)
in_degrees = dict(G.in_degree())



# Add nodes with size proportional to in-degree
for node in G.nodes():
    size = 15 + in_degrees.get(node, 0) * 8  # base size + scaled by in-degree
    # color = "#ff6666" if node == data["root"] else "#66b3ff"
    
    if(node in ui_packages):
        color = "#33ff00"
    else:
        if node in internal_packages:
            color = "#66b3ff"
        else:
            color = "#ff6666"
    if node == data["root"]:
        color = "#ffae00"

    net.add_node(node, size=size, color=color, image="package.svg", title=f"{node} dependencies: {len(list(G.successors(node)))}")

# Add edges
for source, target in G.edges():
    net.add_edge(source, target)

# Save to HTML
net.show("dependencies.html")